homepage_title: Rainbond 文档中心
site_title: Rainbond

url: "https://www.rainbond.com"
baseurl: "/docs"

plugins:
- jekyll-sitemap

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

versions:
  v3.6: v3.6
  v3.7: v3.7
  v5.0: v5.0
  stable: v5.0

release_info:
  v3.6:
    name: v3.6.1
    version: v3.6.1
    build_time: 2018/07/19 16:35:45
    start_time: 2018/07/19 19:33:22.046027038 +800 CST  
  v3.7:
    name: v3.7.2
    version: v3.7.2
    build_time: 2018/08/15 10:13:27
    start_time: 2018/08/15 10:10:14.012472125 +800 CST 
  v5.0:
    name: v5.0.0
    version: v5.0.0
    build_time: 2018/08/30 16:04:31
    start_time: 2018/08/30 16:06:25.016902365 +800 CST 

exclude: ["ci", "vendor"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

algolia:
   application_id: RITXU8D7M1
   index_name: rainbond
