---
baseurl: "https://www.rainbond.com/docs/"
languageCode: "zh-cn"
DefaultContentLanguage: "zh-cn"
title: "Rainbond文档中心(5.1版)"
theme: "hugo-theme-learn"
canonifyURLs: true
params:
  editURL: "https://github.com/goodrain/rainbond-docs/edit/master/content/"
  showVisitedLinks: true
  disableShortcutsTitle: false
outputs:
  home: 
    - HTML
    - RSS 
    - JSON
    - Algolia
outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true