# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Rainbond"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://v5.2-doc.rainbond.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "rainbond"
  homepage = "http://v5.2-doc.rainbond.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
